# Q2 from tutorial 7 assignment
#Authors: Janice Love and Melissa Stephens
#Date: October 11, 2017

import pandas as pd
import numpy as np 
from plotnine import *

#open data
data2 = pd.read_csv("Q2Arcade_CSdegrees.csv", sep = ",", header = 0)

#create plot 
b=ggplot(data2,aes(x="Number of computer science doctorates awarded in the US",y="Total revenue generated by arcades"))
b+geom_point()+coord_cartesian()
# remove grey background
b+geom_point()+coord_cartesian()+theme_bw()

# remove grey background and gridlines, add trendline 
b+geom_point()+coord_cartesian()+theme_classic()+stat_smooth(method="lm")



